# Generated by Django 3.2.7 on 2023-01-07 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20230107_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfriends',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addfriends',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viewfriends',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
