# Generated by Django 3.2.7 on 2023-01-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_viewfriends_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewfriends',
            name='name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x106cecee0>', max_length=50, null=True),
        ),
    ]
