# Generated by Django 3.2.7 on 2023-01-08 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_viewfriends_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewfriends',
            name='name',
        ),
    ]
