# Generated by Django 3.2.7 on 2023-02-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_budget_budgetofuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budgetofUser',
            field=models.IntegerField(default=0),
        ),
    ]
