# Generated by Django 3.2.7 on 2023-02-02 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_budget_budgetofuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='api.budget')),
            ],
        ),
    ]
