# Generated by Django 3.2.7 on 2023-02-03 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_singlepaybudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitPayBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('budgetForSplitPay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgetForSplitPay', to='api.budget')),
                ('friendsList', models.ManyToManyField(blank=True, related_name='friendsList', to='api.Budget')),
            ],
        ),
    ]
